import SwiftUI

/// The map geometry measured at build time by scripts/build-ios-map.js:
/// where each quiz input sits on the map raster, plus the airspace sector
/// overlay text. Positions are in map coordinates (points, origin top-left).
struct MapQuizData: Codable {
    struct Item: Codable {
        enum ItemType: String, Codable {
            case label, airway, vorDegree, boundary
        }

        enum Align: String, Codable {
            case leading, center, trailing
        }

        /// Unique per item: SVG element id + "_" + answer.
        let key: String
        let answer: String
        let type: ItemType
        let x: Double
        let y: Double
        let rotation: Double
        let align: Align
    }

    struct Sector: Codable {
        let x: Double
        let y: Double
        let color: String
        let underlineFirst: Bool
        let lines: [String]
    }

    let width: Double
    let height: Double
    let items: [Item]
    let sectors: [Sector]
}

/// Native port of the quiz logic in map/src.js.
final class MapQuizModel: ObservableObject {
    struct Entry: Identifiable {
        let item: MapQuizData.Item
        var text = ""
        var isWrong = false
        var isLocked = false

        var id: String { item.key }
    }

    let data: MapQuizData
    let mapImage: UIImage

    @Published var entries: [Entry]
    @Published var showSectors = true
    @Published var autocorrect = false {
        didSet {
            if autocorrect { checkAll() }
        }
    }

    init() {
        // Both resources are generated by scripts/build-ios-map.js.
        guard
            let jsonURL = Bundle.main.url(forResource: "mapData", withExtension: "json"),
            let decoded = try? JSONDecoder().decode(MapQuizData.self, from: Data(contentsOf: jsonURL)),
            let pngURL = Bundle.main.url(forResource: "map", withExtension: "png"),
            let image = UIImage(contentsOfFile: pngURL.path)
        else {
            fatalError("missing map resources — run: npm run build:ios-map")
        }
        data = decoded
        mapImage = image
        entries = decoded.items.map { Entry(item: $0) }
    }

    func fillAnswers() {
        for index in entries.indices {
            entries[index].text = entries[index].item.answer
            entries[index].isWrong = false
            entries[index].isLocked = false
        }
    }

    func hint() {
        for index in entries.indices where entries[index].text.isEmpty {
            entries[index].text = String(entries[index].item.answer.prefix(1))
        }
    }

    func reset() {
        for index in entries.indices {
            entries[index].text = ""
            entries[index].isWrong = false
            entries[index].isLocked = false
        }
    }

    func checkAll() {
        for index in entries.indices {
            check(at: index)
        }
    }

    /// Called on every keystroke; only grades in autocorrect mode, like the
    /// website's keyup handler.
    func entryEdited(_ key: String) {
        guard autocorrect, let index = entries.firstIndex(where: { $0.id == key }) else { return }
        check(at: index)
    }

    private func check(at index: Int) {
        let answer = entries[index].item.answer.uppercased()
        let input = entries[index].text.uppercased()
        if entries[index].text != input {
            entries[index].text = input
        }
        entries[index].isWrong = !answer.hasPrefix(input)
        if input == answer {
            entries[index].isLocked = true
        }
    }
}
